# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_album_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='first_name',
        ),
    ]
