# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_musician_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='musician',
            name='hobby',
            field=models.ManyToManyField(to='main.Hobby'),
        ),
    ]
