# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_supermusician'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='first_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
